# For customization options see: https://docs.docker.com/compose/yml/
web:
  build: .
  container_name: roomify_web
  links:
    - db:mysql
  networks:
    - frontend
    - backend
  ports:
    - "32200:80"
  volumes:
    - /var/www/html
    - /var/www/private

db:
  image: mysql
  container_name: roomify_db
  networks:
    - backend
  environment:
    MYSQL_DATABASE: drupal
    MYSQL_USER: drupal
    MYSQL_PASSWORD: drupal
    MYSQL_ROOT_PASSWORD: password
  volumes:
    - rfa-db:/var/lib/mysql
